In [2]:
import numpy as np

1 Dimentional Array

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.size)
print(len(arr)) #In 1D array both size and len gives same output 

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
5


______________________________________________

2 Dimensional Array

In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(type(arr2d))
print(arr2d.size) #Size gives the number of elements present in the array
print(len(arr2d)) #len gives the length of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
9
3


In [13]:
#Check the dimension of the array 
print(arr.ndim)
print(arr2d.ndim)

1
2


In [5]:
#Check the data type of the array elements 
print(arr.dtype) 
print(arr2d.dtype)

int64
int64


In [6]:
#Get the shape(no.of rows, no.of columns) in the array 
print(arr.shape)
print(arr2d.shape)

(5,)
(3, 3)


_________
Zero Array

In [7]:
#Create a array with zero values of length of 10
zero_arr = np.zeros(10,dtype=int) #By default numpy take float datatype 
print(zero_arr)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
#Create 2D array with zero values 
zero_arr2d = np.zeros((3,4),dtype=int) #3 rows, 4 colums
print(zero_arr2d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
#Change datatype from int to float
zero_arr2d.dtype = float
print(zero_arr2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


______
One Array

In [10]:
one_arr = np.ones(10,dtype=int)
print(one_arr)

[1 1 1 1 1 1 1 1 1 1]


In [11]:
one_arr2d = np.ones((4,5),dtype=int)
print(one_arr2d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
print(np.__version__)

2.3.5


____
Full method -> For creating array with the value we want

In [13]:
nums = np.full(12,21) 
print(nums)

[21 21 21 21 21 21 21 21 21 21 21 21]


In [14]:
nums_2d = np.full((5,8),99)
print(nums_2d)

[[99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]]


___
Numpy Operations

In [15]:
num1 = np.array([1,2,3,4])
num2 = np.array([10,20,30,40])
#In numpy we can perfrom Arithmatic operations on 2 or more arrays without using loops
print("Addition:",num1 + num2) 
print("Subtraction", num1 - num2)
print("Multiplication:",num1 * num2)
print("Division:",num1/num2)
print("Floor division:",num1//num2)
print("Exponential:",num2**num1)

Addition: [11 22 33 44]
Subtraction [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Floor division: [0 0 0 0]
Exponential: [     10     400   27000 2560000]


___
Numpy Aggregations:
The process of computing summary satistics such as sum,min,max,mean ect.

In [16]:
arr = np.array([20,34,2,66])
arr2d = np.array([[23,44,23,67],[67,88,54,68]])
print("Sum____")
print(np.sum(arr))
print(np.sum(arr2d))
print("Mean(Average)_____")
print(np.mean(arr))
print(np.mean(arr2d))
print("Min_____")
print(np.min(arr))
print(np.min(arr2d))
print("Max_____")
print(np.max(arr))
print(np.max(arr2d))
print("Median_____")
print(np.median(arr))
print(np.median(arr2d))
print("Variance ____")
print(np.var(arr))
print(np.var(arr2d))
print("STD___")
print(np.std(arr))
print(np.std(arr2d))

Sum____
122
434
Mean(Average)_____
30.5
54.25
Min_____
2
23
Max_____
66
88
Median_____
27.0
60.5
Variance ____
548.75
463.9375
STD___
23.425413550244958
21.53920843485201


____
Conditional Aggregations

In [21]:
print(arr)
print(np.sum(arr[arr > 40]))
print(arr[arr>20]) #We can give the condition inside the sqaure bracket
print("______")
print(arr[arr%2 == 0])

[20 34  2 66]
66
[34 66]
______
[20 34  2 66]


In [23]:
print(np.sum(arr2d,axis=1)) #Sum of elements in column wise
print(np.sum(arr2d,axis=0)) #Sum of elements in row wise

[157 277]
[ 90 132  77 135]


_____
Array Indexing

In [24]:
arr = np.array([23,44,13,56,33,578,93,34,568,334])
print(arr[5])
print(arr[3])

578
56


In [25]:
arr2d = np.array([[23,445,455,323,688,654,6665],[334,554,22,56,77,54,33],[122,345,44,666,444,33,234]])
print(arr2d[2])

[122 345  44 666 444  33 234]


In [49]:
print(arr2d[2,3:])
print(arr2d[2,4])
print(arr2d[0,2:6])
print(arr2d[1,0::2])
print(arr2d[1][0::2])
print(arr2d[0:2,2:6])
print(arr2d[1:,0:3])

[666 444  33 234]
444
[455 323 688 654]
[334  22  77  33]
[334  22  77  33]
[[455 323 688 654]
 [ 22  56  77  54]]
[[334 554  22]
 [122 345  44]]


In [51]:
bool_arr = arr > 30
print(bool_arr)

[False  True False  True  True  True  True  True  True  True]


In [54]:
bool_arr2d = arr2d > 200
print(bool_arr2d)

[[False  True  True  True  True  True  True]
 [ True  True False False False False False]
 [False  True False  True  True False  True]]


____
Reshape -> Used to reshape the array.

Ravel -> Used to flatten the multi dimensional array into a single dimensional array.

Flatten -> Similar to Ravel, but it returns a new copy of a given original array

hstack -> used to join array horizondally 

vstack -> used to join array vertically

In [61]:
print(arr2d.flatten())
print(arr2d.ravel()) #both are similar but flatten returns a new array with diffrent memory address


[  23  445  455  323  688  654 6665  334  554   22   56   77   54   33
  122  345   44  666  444   33  234]
[  23  445  455  323  688  654 6665  334  554   22   56   77   54   33
  122  345   44  666  444   33  234]


In [64]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [70]:
print(np.transpose(arr2d))
print("")
print(arr2d)

[[  23  334  122]
 [ 445  554  345]
 [ 455   22   44]
 [ 323   56  666]
 [ 688   77  444]
 [ 654   54   33]
 [6665   33  234]]

[[  23  445  455  323  688  654 6665]
 [ 334  554   22   56   77   54   33]
 [ 122  345   44  666  444   33  234]]


In [71]:
arr2d.T

array([[  23,  334,  122],
       [ 445,  554,  345],
       [ 455,   22,   44],
       [ 323,   56,  666],
       [ 688,   77,  444],
       [ 654,   54,   33],
       [6665,   33,  234]])