In [2]:
import numpy as np

1 Dimentional Array

In [11]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.size)
print(len(arr)) #In 1D array both size and len gives same output 

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
5


______________________________________________

2 Dimensional Array

In [12]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(type(arr2d))
print(arr2d.size) #Size gives the number of elements present in the array
print(len(arr2d)) #len gives the length of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
9
3


In [13]:
#Check the dimension of the array 
print(arr.ndim)
print(arr2d.ndim)

1
2


In [15]:
#Check the data type of the array elements 
print(arr.dtype) 
print(arr2d.dtype)

int64
int64


In [16]:
#Get the shape(no.of rows, no.of columns) in the array 
print(arr.shape)
print(arr2d.shape)

(5,)
(3, 3)


_________
Zero Array

In [22]:
#Create a array with zero values of length of 10
zero_arr = np.zeros(10,dtype=int) #By default numpy take float datatype 
print(zero_arr)

[0 0 0 0 0 0 0 0 0 0]


In [23]:
#Create 2D array with zero values 
zero_arr2d = np.zeros((3,4),dtype=int) #3 rows, 4 colums
print(zero_arr2d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [27]:
#Change datatype from int to float
zero_arr2d.dtype = float
print(zero_arr2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


______
One Array

In [33]:
one_arr = np.ones(10,dtype=int)
print(one_arr)

[1 1 1 1 1 1 1 1 1 1]


In [34]:
one_arr2d = np.ones((4,5),dtype=int)
print(one_arr2d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [35]:
print(np.__version__)

2.3.5


____
Full method -> For creating array with the value we want

In [36]:
nums = np.full(12,21) 
print(nums)

[21 21 21 21 21 21 21 21 21 21 21 21]


In [40]:
nums_2d = np.full((5,8),99)
print(nums_2d)

[[99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99]]


___
Numpy Operations

In [49]:
num1 = np.array([1,2,3,4])
num2 = np.array([10,20,30,40])
#In numpy we can perfrom Arithmatic operations on 2 or more arrays without using loops
print("Addition:",num1 + num2) 
print("Subtraction", num1 - num2)
print("Multiplication:",num1 * num2)
print("Division:",num1/num2)
print("Floor division:",num1//num2)
print("Exponential:",num2**num1)

Addition: [11 22 33 44]
Subtraction [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Floor division: [0 0 0 0]
Exponential: [     10     400   27000 2560000]
